---
# tasks file for docker-registry.
- name: log into docker hub regitry
  docker_login:
   username: "cyrinebelguith"
   password: "203JFT1712"
- name: tag and push to docker hub
  docker_image:
   name: cd-project 
   repository: cyrinebelguith/cd-angular
   push: yes
